stratis-storage/into-dbus-python

.travis.yml

Begin continuous integration.

---

src/into_dbus_python/_version.py
src/into_dbus_python/_xformer.py
tests/test_signature_parser.py

Raise an exception if struct contains wrong number of values.

---

src/into_dbus_python/_xformer.py

Use comprehension instead of map.

---

src/into_dbus_python/_signature.py
src/into_dbus_python/_version.py
src/into_dbus_python/_xformer.py
tests/test_signature_parser.py
tox.ini

Add a strip_variant_levels parameter.

---

check.py
src/into_dbus_python/_xformer.py
tests/test_signature_parser.py

Do not disable bad-continuation check

---

check.py
src/into_dbus_python/_xformer.py
tests/test_signature_parser.py

Do not disable invalid name check

---

tests/test_signature_parser.py

Do not use strategies.one_of w/ only one strategy argument

---

tests/test_signature_parser.py

Some infrastructure cleanups

---

setup.py

Make package Python3 only

---

tests/test_signature_parser.py

Make test more efficient by not building strategy every time

---

src/into_dbus_python/_version.py

New version: 0.07

---

tox.ini

Related: https://github.com/stratis-storage/project/issues/49.

Have pytest give verbose output

---

setup.py
src/into_dbus_python/_signature.py

No longer omit Unix fds from tests

---

requirements.txt
src/into_dbus_python/__init__.py

Addresses stratis-storage/project#198

Upgrade Python requirements to Fedora 31 defaults

---

src/into_dbus_python/_xformer.py
tests/test_deterministic.py
tests/test_hypothesis.py

Supercedes #33 
Related https://github.com/stratis-storage/project/issues/243

Do not have each transformation function return a tuple

---

CHANGES.txt

Add changelog

---

MANIFEST.in

Related https://github.com/stratis-storage/project/issues/308

Remove check.py from the manifest

---

src/into_dbus_python/_signature.py
src/into_dbus_python/_xformer.py
tests/test_hypothesis.py

Related: stratis-storage/project#456

Switch to literal string interpolation

---

.github/workflows/weekly.yml

Related https://github.com/stratis-storage/project/issues/589

Make pip root directory sibling of default 

---

.github/workflows/weekly.yml

Related https://github.com/stratis-storage/project/issues/634

Update Python version for pip install

---

CHANGES.txt
README.rst
src/into_dbus_python/_errors.py
tests/test_hypothesis.py

Related: stratis-storage/project#663

Fix misspellings

---

.github/workflows/main.yml
Makefile
monkeytype_config.py
src/into_dbus_python/_xformer.py

Related https://github.com/stratis-storage/project/issues/89

Add a monkeytype configuration file and a type rewriter
